# Generated by Django 4.1.4 on 2023-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('head', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
